# -*- mode: ruby -*-
# vi: set ft=ruby :

IMAGE_NAME = "bento/ubuntu-20.04"
NODE_COUNT = (ENV["NODE_COUNT"] || "2").to_i
MASTER_IP = "192.168.50.10"

Vagrant.configure("2") do |config|
  config.ssh.insert_key = false
  config.vm.boot_timeout = 1800

  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.cpus = 2
  end

  config.vm.define "master" do |master|
    master.vm.box = IMAGE_NAME
    master.vm.hostname = "master"
    master.vm.network "private_network", ip: MASTER_IP
    master.vm.provider "virtualbox" do |v|
      v.name = "week11-k8s-master"
    end
    master.vm.provision "shell", path: "setup/bootstrap-common.sh", args: [MASTER_IP, MASTER_IP]
    master.vm.provision "shell", path: "setup/master.sh", args: [MASTER_IP]
  end

  (1..NODE_COUNT).each do |i|
    node_ip = "192.168.50.#{i + 10}"
    config.vm.define "node#{i}" do |node|
      node.vm.box = IMAGE_NAME
      node.vm.hostname = "node#{i}"
      node.vm.network "private_network", ip: node_ip
      node.vm.provider "virtualbox" do |v|
        v.name = "week11-k8s-node#{i}"
      end
      node.vm.provision "shell", path: "setup/bootstrap-common.sh", args: [node_ip, MASTER_IP]
      node.vm.provision "shell", path: "setup/node.sh", args: [MASTER_IP]
    end
  end
end
