VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu/jammy64"
  config.vm.hostname = "week06-runner.local"
  config.vm.boot_timeout = 1200

  config.vm.provider "virtualbox" do |vb|
    vb.memory = 2048
    vb.cpus = 2
    vb.name = "week06-runner.local"
  end

  if Vagrant.has_plugin?("vagrant-vbguest")
    config.vbguest.auto_update = false
  end

  config.vm.network "forwarded_port", guest: 80, host: 3080
  config.vm.network "forwarded_port", guest: 22, host: 3022
  config.vm.network "private_network", ip: "192.168.33.45"

  config.vm.synced_folder ".", "/vagrant"

  config.vm.provision "shell", inline: <<-SHELL
    export DEBIAN_FRONTEND=noninteractive
    sudo apt -y update
    sudo apt install -y software-properties-common git curl ca-certificates gnupg lsb-release
    sudo add-apt-repository --yes --update ppa:ansible/ansible
    sudo apt install -y ansible
  SHELL
end
